spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # ms-usuario (8081)
            - id: ms-usuario
              uri: ${MS_USUARIO_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/usuarios/**
            - id: ms-usuario-regiones
              uri: ${MS_USUARIO_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/regiones/**
            - id: ms-usuario-comunas
              uri: ${MS_USUARIO_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/comunas/**
            - id: ms-usuario-direcciones
              uri: ${MS_USUARIO_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/direcciones/**
            # ms-restaurante (8082)
            - id: ms-restaurante
              uri: ${MS_RESTAURANTE_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/restaurantes/**
            - id: ms-restaurante-catalogos
              uri: ${MS_RESTAURANTE_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/catalogos/**
            - id: ms-restaurante-promociones
              uri: ${MS_RESTAURANTE_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/promociones/**
            # ms-orden (8087)
            - id: ms-orden
              uri: ${MS_ORDEN_URL:http://localhost:8087}
              predicates:
                - Path=/api/v1/ordenes/**
            - id: ms-orden-carritos
              uri: ${MS_ORDEN_URL:http://localhost:8087}
              predicates:
                - Path=/api/v1/carritos/**
            - id: ms-orden-carrito-items
              uri: ${MS_ORDEN_URL:http://localhost:8087}
              predicates:
                - Path=/api/v1/carrito-items/**
            - id: ms-orden-pagos
              uri: ${MS_ORDEN_URL:http://localhost:8087}
              predicates:
                - Path=/api/v1/pagos/**
            - id: ms-orden-metodos-pago
              uri: ${MS_ORDEN_URL:http://localhost:8087}
              predicates:
                - Path=/api/v1/metodos-pago/**
            # ms-delivery (8089)
            - id: ms-delivery
              uri: ${MS_DELIVERY_URL:http://localhost:8089}
              predicates:
                - Path=/api/v1/deliveries/**
            - id: ms-delivery-conductores
              uri: ${MS_DELIVERY_URL:http://localhost:8089}
              predicates:
                - Path=/api/v1/conductores/**
server:
  port: 8080