spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=ms-usuario
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/usuarios/**

spring.cloud.gateway.server.webmvc.routes[1].id=ms-usuario-regiones
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/regiones/**

spring.cloud.gateway.server.webmvc.routes[2].id=ms-usuario-comunas
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/comunas/**

spring.cloud.gateway.server.webmvc.routes[3].id=ms-usuario-direcciones
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/direcciones/**

spring.cloud.gateway.server.webmvc.routes[4].id=ms-restaurante
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/v1/restaurantes/**

spring.cloud.gateway.server.webmvc.routes[5].id=ms-restaurante-catalogos
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/v1/catalogos/**

spring.cloud.gateway.server.webmvc.routes[6].id=ms-restaurante-promociones
spring.cloud.gateway.server.webmvc.routes[6].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/v1/promociones/**

spring.cloud.gateway.server.webmvc.routes[7].id=ms-orden
spring.cloud.gateway.server.webmvc.routes[7].uri=http://localhost:8087
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/v1/ordenes/**

spring.cloud.gateway.server.webmvc.routes[8].id=ms-orden-carritos
spring.cloud.gateway.server.webmvc.routes[8].uri=http://localhost:8087
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/api/v1/carritos/**

spring.cloud.gateway.server.webmvc.routes[9].id=ms-orden-carrito-items
spring.cloud.gateway.server.webmvc.routes[9].uri=http://localhost:8087
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/api/v1/carrito-items/**

spring.cloud.gateway.server.webmvc.routes[10].id=ms-orden-pagos
spring.cloud.gateway.server.webmvc.routes[10].uri=http://localhost:8087
spring.cloud.gateway.server.webmvc.routes[10].predicates[0]=Path=/api/v1/pagos/**

spring.cloud.gateway.server.webmvc.routes[11].id=ms-orden-metodos-pago
spring.cloud.gateway.server.webmvc.routes[11].uri=http://localhost:8087
spring.cloud.gateway.server.webmvc.routes[11].predicates[0]=Path=/api/v1/metodos-pago/**

spring.cloud.gateway.server.webmvc.routes[12].id=ms-delivery
spring.cloud.gateway.server.webmvc.routes[12].uri=http://localhost:8089
spring.cloud.gateway.server.webmvc.routes[12].predicates[0]=Path=/api/v1/deliveries/**

spring.cloud.gateway.server.webmvc.routes[13].id=ms-delivery-conductores
spring.cloud.gateway.server.webmvc.routes[13].uri=http://localhost:8089
spring.cloud.gateway.server.webmvc.routes[13].predicates[0]=Path=/api/v1/conductores/**